{
 "title": "keepalived",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "host",
    "label": "HOST",
    "query": {
     "query": "label_values(container_status,instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "VIP status",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "vip_found{instance=\"$host\"}",
     "legendFormat": "VIP:  {{vip_res}}"
    }
   ]
  },
  {
   "title": "VIP切换次数",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "vip_change_count{instance=\"$host\"}",
     "legendFormat": "VIP Change count  {{vip_res}}"
    }
   ]
  },
  {
   "title": "容器状态",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "container_status{instance=\"$host\"}",
     "legendFormat": "Container_status  Container:{{container_id}}"
    }
   ]
  },
  {
   "title": "容器重启次数",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "container_restart_count{instance=\"$host\"}",
     "legendFormat": "Container_id:{{container_id}} Restart_Count "
    }
   ]
  }
 ]
}