rule_files:
  - /etc/prometheus/rules.yml
global:
  scrape_interval:
  evaluation_interval: 5s
  external_labels:
    monitor: 'codelab-monitor'
# 这里表示抓取对象的配置
scrape_configs:
  - job_name: 'keepalived'
    scrape_interval: 5s  #重写了全局抓取间隔时间，由15秒重写成5秒
    static_configs:
      - targets: ['192.168.7.2:2112']
  - job_name: 'prometheus'
    scrape_interval: 5s  #重写了全局抓取间隔时间，由15秒重写成5秒
    static_configs:
      - targets: ['localhost:9090','192.168.7.2:9100']
alerting:
  alertmanagers:
    - static_configs:
        - targets: ['alertmanager:9093']
