version: '3.8'

services:
  keepalived_exporter:
    image: registry.cn-hangzhou.aliyuncs.com/pro-exporter/promexporter:keepalived
    container_name: keepalived_exporter
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    network_mode: "host"
    ports:
      - "2112:2112"
    environment:
      - PORT=2112
    command: ["/keepalived_expoter", "-container_name", "keepalived-master,keepalived-master1", "-vip", "192.168.7.123,192.168.7.124"]
